[package]
name = "gamma-lut-macro"
version = "0.1.0"
authors = ["eV <ev@7pr.xyz>"]
edition = "2018"

[dependencies]
syn = { version = "0.15", features = ["full"] }
quote = "0.6"
proc-macro2 = "0.4.26"
proc-macro-hack = "0.5"

[lib]
proc-macro = true
